/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
import { appDataSchema as alby_zod_ts } from "../apps/alby/src/zod";
import { appDataSchema as basecamp3_zod_ts } from "../apps/basecamp3/src/zod";
import { appDataSchema as btcpayserver_zod_ts } from "../apps/btcpayserver/src/zod";
import { appDataSchema as closecom_zod_ts } from "../apps/closecom/src/zod";
import { appDataSchema as dailyvideo_zod_ts } from "../apps/dailyvideo/src/zod";
import { appDataSchema as databuddy_zod_ts } from "../apps/databuddy/src/zod";
import { appDataSchema as dub_zod_ts } from "../apps/dub/src/zod";
import { appDataSchema as fathom_zod_ts } from "../apps/fathom/src/zod";
import { appDataSchema as feishucalendar_zod_ts } from "../apps/feishucalendar/src/zod";
import { appDataSchema as ga4_zod_ts } from "../apps/ga4/src/zod";
import { appDataSchema as giphy_zod_ts } from "../apps/giphy/src/zod";
import { appDataSchema as googlecalendar_zod_ts } from "../apps/googlecalendar/src/zod";
import { appDataSchema as googlevideo_zod_ts } from "../apps/googlevideo/src/zod";
import { appDataSchema as gtm_zod_ts } from "../apps/gtm/src/zod";
import { appDataSchema as hitpay_zod_ts } from "../apps/hitpay/src/zod";
import { appDataSchema as hubspot_zod_ts } from "../apps/hubspot/src/zod";
import { appDataSchema as insihts_zod_ts } from "../apps/insihts/src/zod";
import { appDataSchema as intercom_zod_ts } from "../apps/intercom/src/zod";
import { appDataSchema as jelly_zod_ts } from "../apps/jelly/src/zod";
import { appDataSchema as jitsivideo_zod_ts } from "../apps/jitsivideo/src/zod";
import { appDataSchema as larkcalendar_zod_ts } from "../apps/larkcalendar/src/zod";
import { appDataSchema as make_zod_ts } from "../apps/make/src/zod";
import { appDataSchema as matomo_zod_ts } from "../apps/matomo/src/zod";
import { appDataSchema as metapixel_zod_ts } from "../apps/metapixel/src/zod";
import { appDataSchema as mock_payment_app_zod_ts } from "../apps/mock-payment-app/src/zod";
import { appDataSchema as nextcloudtalk_zod_ts } from "../apps/nextcloudtalk/src/zod";
import { appDataSchema as office365calendar_zod_ts } from "../apps/office365calendar/src/zod";
import { appDataSchema as office365video_zod_ts } from "../apps/office365video/src/zod";
import { appDataSchema as paypal_zod_ts } from "../apps/paypal/src/zod";
import { appDataSchema as pipedrive_crm_zod_ts } from "../apps/pipedrive-crm/src/zod";
import { appDataSchema as plausible_zod_ts } from "../apps/plausible/src/zod";
import { appDataSchema as posthog_zod_ts } from "../apps/posthog/src/zod";
import { appDataSchema as qr_code_zod_ts } from "../apps/qr_code/src/zod";
import { appDataSchema as routing_forms_zod_ts } from "../apps/routing-forms/src/zod";
import { appDataSchema as salesforce_zod_ts } from "../apps/salesforce/src/zod";
import { appDataSchema as shimmervideo_zod_ts } from "../apps/shimmervideo/src/zod";
import { appDataSchema as stripepayment_zod_ts } from "../apps/stripepayment/src/zod";
import { appDataSchema as tandemvideo_zod_ts } from "../apps/tandemvideo/src/zod";
import { appDataSchema as twipla_zod_ts } from "../apps/twipla/src/zod";
import { appDataSchema as umami_zod_ts } from "../apps/umami/src/zod";
import { appDataSchema as vital_zod_ts } from "../apps/vital/src/zod";
import { appDataSchema as webex_zod_ts } from "../apps/webex/src/zod";
import { appDataSchema as zapier_zod_ts } from "../apps/zapier/src/zod";
import { appDataSchema as zoho_bigin_zod_ts } from "../apps/zoho-bigin/src/zod";
import { appDataSchema as zohocalendar_zod_ts } from "../apps/zohocalendar/src/zod";
import { appDataSchema as zohocrm_zod_ts } from "../apps/zohocrm/src/zod";
import { appDataSchema as zoomvideo_zod_ts } from "../apps/zoomvideo/src/zod";
import { appDataSchema as booking_pages_tag_zod_ts } from "../templates/booking-pages-tag/zod";
import { appDataSchema as event_type_app_card_zod_ts } from "../templates/event-type-app-card/zod";
export const appDataSchemas = {
  alby: alby_zod_ts,
  basecamp3: basecamp3_zod_ts,
  btcpayserver: btcpayserver_zod_ts,
  closecom: closecom_zod_ts,
  dailyvideo: dailyvideo_zod_ts,
  databuddy: databuddy_zod_ts,
  dub: dub_zod_ts,
  fathom: fathom_zod_ts,
  feishucalendar: feishucalendar_zod_ts,
  ga4: ga4_zod_ts,
  giphy: giphy_zod_ts,
  googlecalendar: googlecalendar_zod_ts,
  googlevideo: googlevideo_zod_ts,
  gtm: gtm_zod_ts,
  hitpay: hitpay_zod_ts,
  hubspot: hubspot_zod_ts,
  insihts: insihts_zod_ts,
  intercom: intercom_zod_ts,
  jelly: jelly_zod_ts,
  jitsivideo: jitsivideo_zod_ts,
  larkcalendar: larkcalendar_zod_ts,
  make: make_zod_ts,
  matomo: matomo_zod_ts,
  metapixel: metapixel_zod_ts,
  "mock-payment-app": mock_payment_app_zod_ts,
  nextcloudtalk: nextcloudtalk_zod_ts,
  office365calendar: office365calendar_zod_ts,
  office365video: office365video_zod_ts,
  paypal: paypal_zod_ts,
  "pipedrive-crm": pipedrive_crm_zod_ts,
  plausible: plausible_zod_ts,
  posthog: posthog_zod_ts,
  qr_code: qr_code_zod_ts,
  "routing-forms": routing_forms_zod_ts,
  salesforce: salesforce_zod_ts,
  shimmervideo: shimmervideo_zod_ts,
  stripe: stripepayment_zod_ts,
  tandemvideo: tandemvideo_zod_ts,
  twipla: twipla_zod_ts,
  umami: umami_zod_ts,
  vital: vital_zod_ts,
  webex: webex_zod_ts,
  zapier: zapier_zod_ts,
  "zoho-bigin": zoho_bigin_zod_ts,
  zohocalendar: zohocalendar_zod_ts,
  zohocrm: zohocrm_zod_ts,
  zoomvideo: zoomvideo_zod_ts,
  "booking-pages-tag": booking_pages_tag_zod_ts,
  "event-type-app-card": event_type_app_card_zod_ts,
};
