/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
import dynamic from "next/dynamic";
export const InstallAppButtonMap = {
  exchange2013calendar: dynamic(() => import("../apps/exchange2013calendar/src/components/InstallAppButton")),
  exchange2016calendar: dynamic(() => import("../apps/exchange2016calendar/src/components/InstallAppButton")),
  office365video: dynamic(() => import("../apps/office365video/src/components/InstallAppButton")),
  vital: dynamic(() => import("../apps/vital/src/components/InstallAppButton")),
};
export const AppSettingsComponentsMap = {
  weather_in_your_calendar: dynamic(
    () => import("../apps/weather_in_your_calendar/src/components/AppSettingsInterface")
  ),
  zapier: dynamic(() => import("../apps/zapier/src/components/AppSettingsInterface")),
  "general-app-settings": dynamic(
    () => import("../templates/general-app-settings/components/AppSettingsInterface")
  ),
};
export const EventTypeAddonMap = {
  alby: dynamic(() => import("../apps/alby/src/components/EventTypeAppCardInterface")),
  basecamp3: dynamic(() => import("../apps/basecamp3/src/components/EventTypeAppCardInterface")),
  btcpayserver: dynamic(() => import("../apps/btcpayserver/src/components/EventTypeAppCardInterface")),
  closecom: dynamic(() => import("../apps/closecom/src/components/EventTypeAppCardInterface")),
  databuddy: dynamic(() => import("../apps/databuddy/src/components/EventTypeAppCardInterface")),
  fathom: dynamic(() => import("../apps/fathom/src/components/EventTypeAppCardInterface")),
  ga4: dynamic(() => import("../apps/ga4/src/components/EventTypeAppCardInterface")),
  giphy: dynamic(() => import("../apps/giphy/src/components/EventTypeAppCardInterface")),
  gtm: dynamic(() => import("../apps/gtm/src/components/EventTypeAppCardInterface")),
  hitpay: dynamic(() => import("../apps/hitpay/src/components/EventTypeAppCardInterface")),
  hubspot: dynamic(() => import("../apps/hubspot/src/components/EventTypeAppCardInterface")),
  insihts: dynamic(() => import("../apps/insihts/src/components/EventTypeAppCardInterface")),
  matomo: dynamic(() => import("../apps/matomo/src/components/EventTypeAppCardInterface")),
  metapixel: dynamic(() => import("../apps/metapixel/src/components/EventTypeAppCardInterface")),
  "mock-payment-app": dynamic(
    () => import("../apps/mock-payment-app/src/components/EventTypeAppCardInterface")
  ),
  paypal: dynamic(() => import("../apps/paypal/src/components/EventTypeAppCardInterface")),
  "pipedrive-crm": dynamic(() => import("../apps/pipedrive-crm/src/components/EventTypeAppCardInterface")),
  plausible: dynamic(() => import("../apps/plausible/src/components/EventTypeAppCardInterface")),
  posthog: dynamic(() => import("../apps/posthog/src/components/EventTypeAppCardInterface")),
  qr_code: dynamic(() => import("../apps/qr_code/src/components/EventTypeAppCardInterface")),
  salesforce: dynamic(() => import("../apps/salesforce/src/components/EventTypeAppCardInterface")),
  stripepayment: dynamic(() => import("../apps/stripepayment/src/components/EventTypeAppCardInterface")),
  twipla: dynamic(() => import("../apps/twipla/src/components/EventTypeAppCardInterface")),
  umami: dynamic(() => import("../apps/umami/src/components/EventTypeAppCardInterface")),
  "zoho-bigin": dynamic(() => import("../apps/zoho-bigin/src/components/EventTypeAppCardInterface")),
  zohocrm: dynamic(() => import("../apps/zohocrm/src/components/EventTypeAppCardInterface")),
  "booking-pages-tag": dynamic(
    () => import("../templates/booking-pages-tag/components/EventTypeAppCardInterface")
  ),
  "event-type-app-card": dynamic(
    () => import("../templates/event-type-app-card/components/EventTypeAppCardInterface")
  ),
};
export const EventTypeSettingsMap = {
  alby: dynamic(() => import("../apps/alby/src/components/EventTypeAppSettingsInterface")),
  basecamp3: dynamic(() => import("../apps/basecamp3/src/components/EventTypeAppSettingsInterface")),
  btcpayserver: dynamic(() => import("../apps/btcpayserver/src/components/EventTypeAppSettingsInterface")),
  databuddy: dynamic(() => import("../apps/databuddy/src/components/EventTypeAppSettingsInterface")),
  fathom: dynamic(() => import("../apps/fathom/src/components/EventTypeAppSettingsInterface")),
  ga4: dynamic(() => import("../apps/ga4/src/components/EventTypeAppSettingsInterface")),
  giphy: dynamic(() => import("../apps/giphy/src/components/EventTypeAppSettingsInterface")),
  gtm: dynamic(() => import("../apps/gtm/src/components/EventTypeAppSettingsInterface")),
  hitpay: dynamic(() => import("../apps/hitpay/src/components/EventTypeAppSettingsInterface")),
  metapixel: dynamic(() => import("../apps/metapixel/src/components/EventTypeAppSettingsInterface")),
  paypal: dynamic(() => import("../apps/paypal/src/components/EventTypeAppSettingsInterface")),
  plausible: dynamic(() => import("../apps/plausible/src/components/EventTypeAppSettingsInterface")),
  qr_code: dynamic(() => import("../apps/qr_code/src/components/EventTypeAppSettingsInterface")),
  stripepayment: dynamic(() => import("../apps/stripepayment/src/components/EventTypeAppSettingsInterface")),
};
