/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
export const CalendarServiceMap =
  process.env.NEXT_PUBLIC_IS_E2E === "1"
    ? {}
    : {
        applecalendar: import("../apps/applecalendar/src/lib/CalendarService"),
        caldavcalendar: import("../apps/caldavcalendar/src/lib/CalendarService"),
        exchange2013calendar: import("../apps/exchange2013calendar/src/lib/CalendarService"),
        exchange2016calendar: import("../apps/exchange2016calendar/src/lib/CalendarService"),
        exchangecalendar: import("../apps/exchangecalendar/src/lib/CalendarService"),
        feishucalendar: import("../apps/feishucalendar/src/lib/CalendarService"),
        googlecalendar: import("../apps/googlecalendar/src/lib/CalendarService"),
        "ics-feedcalendar": import("../apps/ics-feedcalendar/src/lib/CalendarService"),
        larkcalendar: import("../apps/larkcalendar/src/lib/CalendarService"),
        office365calendar: import("../apps/office365calendar/src/lib/CalendarService"),
        zohocalendar: import("../apps/zohocalendar/src/lib/CalendarService"),
      };
