/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
export const CrmServiceMap = {
  closecom: import("../apps/closecom/src/lib/CrmService"),
  hubspot: import("../apps/hubspot/src/lib/CrmService"),
  "pipedrive-crm": import("../apps/pipedrive-crm/src/lib/CrmService"),
  salesforce: import("../apps/salesforce/src/lib/CrmService"),
  "zoho-bigin": import("../apps/zoho-bigin/src/lib/CrmService"),
  zohocrm: import("../apps/zohocrm/src/lib/CrmService"),
};
