/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
export const PaymentServiceMap = {
  alby: import("../apps/alby/src/lib/PaymentService"),
  btcpayserver: import("../apps/btcpayserver/src/lib/PaymentService"),
  hitpay: import("../apps/hitpay/src/lib/PaymentService"),
  "mock-payment-app": import("../apps/mock-payment-app/src/lib/PaymentService"),
  paypal: import("../apps/paypal/src/lib/PaymentService"),
  stripepayment: import("../apps/stripepayment/src/lib/PaymentService"),
};
