/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
export const VideoApiAdapterMap =
  process.env.NEXT_PUBLIC_IS_E2E === "1"
    ? {}
    : {
        dailyvideo: import("../apps/dailyvideo/src/lib/VideoApiAdapter"),
        huddle01video: import("../apps/huddle01video/src/lib/VideoApiAdapter"),
        jelly: import("../apps/jelly/src/lib/VideoApiAdapter"),
        jitsivideo: import("../apps/jitsivideo/src/lib/VideoApiAdapter"),
        nextcloudtalk: import("../apps/nextcloudtalk/src/lib/VideoApiAdapter"),
        office365video: import("../apps/office365video/src/lib/VideoApiAdapter"),
        shimmervideo: import("../apps/shimmervideo/src/lib/VideoApiAdapter"),
        sylapsvideo: import("../apps/sylapsvideo/src/lib/VideoApiAdapter"),
        tandemvideo: import("../apps/tandemvideo/src/lib/VideoApiAdapter"),
        webex: import("../apps/webex/src/lib/VideoApiAdapter"),
        zoomvideo: import("../apps/zoomvideo/src/lib/VideoApiAdapter"),
      };
